# Generated by Django 5.1.7 on 2025-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('Explanation', models.TextField()),
            ],
        ),
    ]
